export const environment = {
  production: true,
  OAUTH_CONSUMER_PUBLIC: '<YOUR_OAUTH_CONSUMER_PUBLIC>',
  OAUTH_CONSUMER_SECRET: '<YOUR_OAUTH_CONSUMER_SECRET>',
  OAUTH_SIGNATURE_METHOD: '<YOUR_OAUTH_SIGNATURE_METHOD>',
  TOKEN_PUBLIC: '<YOUR_TOKEN_PUBLIC>',
  TOKEN_SECRET: '<YOUR_TOKEN_SECRET>',
};
